# Inserts a blank line between shell prompts
add_newline = true

[aws]
format = "on [$symbol$profile]($style) "
style = "bold blue"
symbol = "ğŸ…° "

[aws.profile_aliases]
Enterprise_Naming_Scheme-voidstars = 'void**'

# Replace the "â¯" symbol in the prompt with "âœ"
[character]                            # The name of the module we are configuring is "character"
success_symbol = "[âœ](bold green)"     # The "success_symbol" segment is being set to "âœ" with the color "bold green"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

# @todo temporary disable on Rust. This becoes unbearably slow in the "dot"
# repo. It appears to only happen after adding the cargo run bin metadata to the
# Cargo.toml. File an issue for this and then fix when fix is up.
[rust]
disabled = true
